config/routes.rb
Appfy::Application.routes.draw do
  delete "section/destroy"

  match 'pages/:id/add_component' => 'pages#add_component',
        :as => :pages_add_component,  :via => :post
  match 'pages/:id/delete_component' => 'pages#delete_component',
        :as => :pages_delete_component,  :via => :post
  match 'pages/:id/update_component' => 'pages#update_component',
        :as => :pages_update_component, :via => :post
  match 'pages/:id/components' => 'pages#components',
        :as => :pages_components, :via => :get

  resources :apps do
    member do
    	get 'data'
    	get 'design'
    	get 'admin_panel'
      post 'add_section'
      post 'delete_section'
      get 'preview'
    end
  end


  resources :categories


  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users
end

app/views/apps/_contact_design_panel.html.erb
wefwefwef

app/views/apps/_form.html.erb
<%= simple_form_for(@app) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name, :require => true , label: t("name") %>
    <%= f.association  :category, label_method: :select_label, :require => true, prompt: t("choose_category"), label: t("category"), input_html: { :style => "font-family:FontAwesome;"} %>
	  <%= image_tag @app.icon.url(:normal), :class => "well well-small" %>
    <%= f.input :icon, label: I18n.t("change_icon", :default => "Change Icon")  %>
    <%= image_tag @app.splash_screen.url(:iphone4), :class => "well well-small" %>
    <%= f.input :splash_screen, label: I18n.t("change_splash_screen", :default => "Change splash screen image") %>

    <%= f.input :description, label: t("description")  %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/apps/_galery_design_panel.html.erb
wefwefwef

app/views/apps/_home_design_panel.html.erb
<a href="#myModal" role="button" class="btn" data-toggle="modal">Launch demo modal</a>
<%= content_for :modal do %>
	<%= render 'component_picker_modal', sec: sec %>
<% end %>
<div id="accordion-<%= sec.id %>" class="accordion">
	<div class="accordion-group">
		<div class="accordion-heading">
			<a href="#collapse-title" data-parent="#accordion2" data-toggle="collapse" class="accordion-toggle">
				Title
			</a>
		</div>

		<div class="accordion-body in collapse" id="collapse-title" style="height: auto;">
			<div class="accordion-inner">
				<%= render "apps/comp_form/title", sec: sec %>
			</div>
		</div>
	</div>

	<% sec.page.pageconfig.components.each_with_index do |c , i| %>
		<%= render :file => "apps/_home_design_panel_item.html.erb", :locals => { c: c, i: i, sec: sec } %>
	<% end %>

</div>

app/views/apps/_home_design_panel_item.html.erb
<%
    xtype = c
    xtype = c["xtype"] if c.class == Hash
%>

<div class="accordion-group">
    <div class="accordion-heading">
        <a <% if i %>href="#<%= "collapse-#{i}" %>"<% end %> data-parent="" data-toggle="collapse" class="accordion-toggle collapsed">
            <%= xtype %>
        </a>
    </div>

    <div class="reorder_icon">
        <a href="#" class="btn btn-minier btn-info">
            <i class="icon-only icon-reorder"></i>
        </a>
    </div>

    <div class="bt_tools">
        <a <% if i %>data-array-id="<%= i %>"<% end %> data-sec-id="<%= sec.id %>" href="#" class="btn btn-minier btn-danger delete_component">
            <i class="icon-only icon-remove"></i>
        </a>
    </div>

    <div class="accordion-body collapse" <% if i %>id="<%= "collapse-#{i}" %>"<% end %>>
        <div class="accordion-inner">
            <%= render :file => "apps/comp_form/_#{xtype}.html.erb", :locals => { sec: sec } %>
        </div>
    </div>
</div>

app/views/apps/_list_design_panel.html.erb
wefwefwef

app/views/apps/_map_design_panel.html.erb
wefwefwef

app/views/apps/_new_section_form.html.erb
<%= simple_form_for(@section, :url => add_section_app_path, :method => :post) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name, :require => true , label: t("name") %> 
    <span><%= I18n.t("pagetype", :default => "Page Type") %></span>
    <select name="section[pagetype]" class="pagetypepicker">
      <option value=""></option>
	  <option data-img-src="/assets/sec-home.png" value="home">  home  </option>
	  <option data-img-src="/assets/sec-list.png" value="list">  list  </option>
	  <option data-img-src="/assets/sec-simple.png" value="simple">  simple  </option>
	  <option data-img-src="/assets/sec-galery.png" value="galery">  galery  </option>
	  <option data-img-src="/assets/sec-contact.png" value="contact">  contact  </option>
	  <option data-img-src="/assets/sec-map.png" value="map">  map  </option>
	</select>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/apps/data.html.erb
data.html.erb

app/views/apps/design.html.erb
<div class="span8">
	<div class="widget-header" style="text-align: left">
		<div class="widget-toolbar no-border">
			<ul class="nav nav-tabs" id="myTab">
				<li>
					<a href="#menu_design" data-toggle="tab"><%= I18n.t("menu_design", :default => "Menu Creation") %></a>
				</li>

				<% @app.sections.each do |sec| %>
					<li>
						<a href="#<%= "tab-#{sec.id}" %>" data-toggle="tab"><%= sec.name %>
							<button class="delete_section" type="button" id-section="<%= sec.id %>" data-dismiss="alert">
				                <i class="icon-remove"></i>
				            </button>
						</a>
					</li>
				<% end %>
			</ul>
		</div>
	</div>

	<div class="widget-body">
		<div class="widget-main padding-6">
			<div class="tab-content">
				<div class="tab-pane" id="menu_design">
					<%= render 'new_section_form' %>
				</div>
				<% @app.sections.each do |sec| %>
					<div class="tab-pane" id="<%= "tab-#{sec.id}" %>">
						<%= render "#{sec.pagetype}_design_panel", sec: sec %>
					</div>
				<% end %>
			</div>
		</div>
	</div>
</div>

<div class="span4" style="text-align: left;">
	<%= render 'preview' %>
</div>

<% content_for :js do %>

<script type="text/javascript" src="http://api.map.baidu.com/api?v=1.3"></script>
<script type="text/javascript">
<!--

    var urls = {
        addComponent: '<%= pages_add_component_path(@app) %>',
        deleteComponent: '<%= pages_delete_component_path(@app) %>',
        deleteSection: '<%= section_destroy_path %>'
    };

    $('.image-component').each(function() {
        $(this).ace_file_input({
            no_file: 'No File ...',
            btn_choose: 'Choose',
            btn_change: 'Change',
            droppable: false,
            onchange: null,
            thumbnail: false //| true | large
            //whitelist:'gif|png|jpg|jpeg'
            //blacklist:'exe|php'
            //onchange:''
            //
        });
    });

// -->
</script>

<script type="text/javascript">
<!--
    var map = document.getElementById('map-container');

    function initMap(selector) {
        var bmap = BMap;

        baidu_map = new bmap.Map(selector);
        baidu_localSearch = new bmap.LocalSearch(baidu_map);
        baidu_map.enableScrollWheelZoom();    //启用滚轮放大缩小，默认禁用
        baidu_map.enableContinuousZoom();    //启用地图惯性拖拽，默认禁用
        baidu_map.addControl(new bmap.NavigationControl());  //添加默认缩放平移控件
        baidu_map.addControl(new bmap.OverviewMapControl()); //添加默认缩略地图控件
        baidu_localSearch.enableAutoViewport(); //允许自动调节窗体大小
    }

    if (map !== null) {
        initMap('map-container');
    }
// -->
</script>

<% end %>

app/views/apps/edit.html.erb
<h1><%= t("Editing app") %></h1>

<%= render 'form' %>
<%= link_to t('Show'), @app %> |
<%= link_to t('Back'), apps_path %>

app/views/apps/index.html.erb
<h1>Listing apps</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Category</th>
    <th>Description</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @apps.each do |app| %>
  <tr>
    <td><%= app.name %></td>
    <td><%= app.category_id %></td>
    <td><%= app.description %></td>
    <td><%= app.user_id %></td>
    <td><%= link_to t('Show'), app %></td>
    <td><%= link_to t('Edit'), edit_app_path(app) %></td>
    <td><%= link_to t('Destroy'), app, method: :delete, data: { confirm: t('Are you sure?') } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to t('New App'), new_app_path %>

app/views/apps/new.html.erb
<h2><%= I18n.t("New app") %></h2>

<%= render 'form' %>

<%= link_to t('Back'), apps_path %>

app/views/apps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b><%= I18n.t("app_name", :default => "App name") %>:</b>
  <%= @app.name %>
</p>

<p>
  <b><%= I18n.t("category", :default => "Category") %>:</b>
  <i class='<%= @app.category.icon_css %>'></i> <%= @app.category.name %>
</p>
<p>
<b><%= I18n.t("app_icon", :default => "App Icon") %>:</b>
<%= image_tag @app.icon.url(:normal), :class => "well well-small" %>
</p>
<p>
<b><%= I18n.t("splash_screen", :default => "Splash screen") %>:</b>
<%= image_tag @app.splash_screen.url(:iphone4), :class => "well well-small" %>
</p>
<p>
  <b><%= I18n.t("description", :default => "Description") %>:</b>
  <%= @app.description %>
</p>

<%= link_to I18n.t("edit", :default => 'Edit'), edit_app_path(@app) %> |
<%= link_to I18n.t("back", :default => 'Back'), apps_path %>