config/routes.rb
Appfy::Application.routes.draw do
  delete "section/destroy"

  match 'pages/:id/add_component' => 'pages#add_component',
        :as => :pages_add_component,  :via => :post
  match 'pages/:id/delete_component' => 'pages#delete_component',
        :as => :pages_delete_component,  :via => :post
  match 'pages/:id/update_component' => 'pages#update_component',
        :as => :pages_update_component, :via => :post
  match 'pages/:id/components' => 'pages#components',
        :as => :pages_components, :via => :get

  resources :apps do
    member do
    	get 'data'
    	get 'design'
    	get 'admin_panel'
      post 'add_section'
      post 'delete_section'
      get 'preview'
    end
  end


  resources :categories


  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users
end

app/views/layouts/_leftmenu.html.erb
      <div id="sidebar">
        <div id="sidebar-shortcuts">
          <div id="sidebar-shortcuts-large">
            <%= link_to "<i class='icon-plus'></i>#{t('new_app', :default => 'New App')}".html_safe , new_app_path, :class => "btn btn-small btn-success" %>
          </div>

          <div id="sidebar-shortcuts-mini">
            <span class="btn btn-success"></span>

            <span class="btn btn-info"></span>

            <span class="btn btn-warning"></span>

            <span class="btn btn-danger"></span>
          </div>
        </div><!--#sidebar-shortcuts-->

        <ul class="nav nav-list">
          
          <li id="menu-users-show">
            <%= link_to "<i class='icon-dashboard'></i><span>#{t('dashboard', :default => 'Dashboard')}</span>".html_safe, user_path(current_user) unless current_user.nil? %>              
            </a>
          </li>

          <% current_user.apps.each_with_index do |app, i | %>
          <li id="menu-apps-<%= app.id %>">
            <a href="#" class="dropdown-toggle">
              <i class="<%= app.category.icon_css %>"></i>
              <span><%= app.name %></span>

              <b class="arrow icon-angle-down"></b>
            </a>
            <ul class="submenu" style="display: none;">


              <li id="menu-apps-design-<%= app.id %>">
                <%= link_to "<i class='icon-double-angle-right'></i>#{t('design', :default => 'App\'s Design')}".html_safe, design_app_path(app) %>
              </li>              
              <li id="menu-apps-data-<%= app.id %>">
                <%= link_to "<i class='icon-double-angle-right'></i>#{t('data_management', :default => 'Data Management')}".html_safe, data_app_path(app) %>
              </li>

              <li id="menu-apps-show-<%= app.id %>">
                <%= link_to "<i class='icon-double-angle-right'></i>#{t('stat', :default => 'Statistic')}".html_safe, app_path(app) %>
              </li>
              <li id="menu-apps-edit-<%= app.id %>">
                <%= link_to "<i class='icon-double-angle-right'></i>#{t('general_settings', :default => 'General Settings')}".html_safe, edit_app_path(app) %>
              </li>
              <li id="menu-apps-admin_panel-<%= app.id %>">
                <%= link_to "<i class='icon-double-angle-right'></i>#{t('admin_panel', :default => 'Admin Panel')}".html_safe, admin_panel_app_path(app) %>
              </li>

            </ul>
          <li>
          <% end %>


          <!-- <li>
            <a href="typography.html">
              <i class="icon-text-width"></i>
              <span>Typography</span>
            </a>
          </li>

          <li>
            <a href="#" class="dropdown-toggle">
              <i class="icon-desktop"></i>
              <span>UI Elements</span>

              <b class="arrow icon-angle-down"></b>
            </a>

            <ul class="submenu">
              <li>
                <a href="elements.html">
                  <i class="icon-double-angle-right"></i>
                  Elements
                </a>
              </li>

              <li>
                <a href="buttons.html">
                  <i class="icon-double-angle-right"></i>
                  Buttons &amp; Icons
                </a>
              </li>

              <li>
                <a href="treeview.html">
                  <i class="icon-double-angle-right"></i>
                  Treeview
                </a>
              </li>
            </ul>
          </li>

          <li>
            <a href="tables.html">
              <i class="icon-list"></i>
              <span>Tables</span>
            </a>
          </li>

          <li>
            <a href="#" class="dropdown-toggle">
              <i class="icon-edit"></i>
              <span>Forms</span>

              <b class="arrow icon-angle-down"></b>
            </a>

            <ul class="submenu">
              <li>
                <a href="form-elements.html">
                  <i class="icon-double-angle-right"></i>
                  Form Elements
                </a>
              </li>

              <li>
                <a href="form-wizard.html">
                  <i class="icon-double-angle-right"></i>
                  Wizard &amp; Validation
                </a>
              </li>

              <li>
                <a href="wysiwyg.html">
                  <i class="icon-double-angle-right"></i>
                  Wysiwyg &amp; Markdown
                </a>
              </li>
            </ul>
          </li>

          <li>
            <a href="widgets.html">
              <i class="icon-list-alt"></i>
              <span>Widgets</span>
            </a>
          </li>

          <li>
            <a href="calendar.html">
              <i class="icon-calendar"></i>
              <span>Calendar</span>
            </a>
          </li>

          <li>
            <a href="gallery.html">
              <i class="icon-picture"></i>
              <span>Gallery</span>
            </a>
          </li>

          <li>
            <a href="grid.html">
              <i class="icon-th"></i>
              <span>Grid</span>
            </a>
          </li>

          <li class="active open">
            <a href="#" class="dropdown-toggle">
              <i class="icon-file"></i>
              <span>Other Pages</span>

              <b class="arrow icon-angle-down"></b>
            </a>

            <ul class="submenu">
              <li>
                <a href="pricing.html">
                  <i class="icon-double-angle-right"></i>
                  Pricing Tables
                </a>
              </li>

              <li>
                <a href="invoice.html">
                  <i class="icon-double-angle-right"></i>
                  Invoice
                </a>
              </li>

              <li>
                <a href="login.html">
                  <i class="icon-double-angle-right"></i>
                  Login &amp; Register
                </a>
              </li>

              <li>
                <a href="error-404.html">
                  <i class="icon-double-angle-right"></i>
                  Error 404
                </a>
              </li>

              <li>
                <a href="error-500.html">
                  <i class="icon-double-angle-right"></i>
                  Error 500
                </a>
              </li>

              <li class="active">
                <a href="blank.html">
                  <i class="icon-double-angle-right"></i>
                  Blank Page
                </a>
              </li>
            </ul>
          </li>
        </ul>-->
        <!--/.nav-list -->

        <div id="sidebar-collapse">
          <i class="icon-double-angle-left"></i>
        </div> 
      </div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Appfy", root_path, :class => 'brand' %>
<ul class="nav">
  <% if user_signed_in? %>
    <li>
    <%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %>
    </li>
  <% else %>
    <li>
    <%= link_to 'Login', new_user_session_path %>
    </li>
  <% end %>
  <% if user_signed_in? %>
    <li>
    <%= link_to 'Edit account', edit_user_registration_path %>
    </li>
  <% else %>
    <li>
    <%= link_to 'Sign up', new_user_registration_path %>
    </li>
  <% end %>
</ul>

app/views/layouts/_topleftnotifier.html.erb
          <ul class="nav ace-nav pull-right">
            <li class="grey">
              <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                <i class="icon-tasks"></i>
                <span class="badge badge-grey">4</span>
              </a>

              <ul class="pull-right dropdown-navbar dropdown-menu dropdown-caret dropdown-closer">
                <li class="nav-header">
                  <i class="icon-ok"></i>
                  4 Tasks to complete
                </li>

                <li>
                  <a href="#">
                    <div class="clearfix">
                      <span class="pull-left">Software Update</span>
                      <span class="pull-right">65%</span>
                    </div>

                    <div class="progress progress-mini ">
                      <div style="width:65%" class="bar"></div>
                    </div>
                  </a>
                </li>

                <li>
                  <a href="#">
                    <div class="clearfix">
                      <span class="pull-left">Hardware Upgrade</span>
                      <span class="pull-right">35%</span>
                    </div>

                    <div class="progress progress-mini progress-danger">
                      <div style="width:35%" class="bar"></div>
                    </div>
                  </a>
                </li>

                <li>
                  <a href="#">
                    <div class="clearfix">
                      <span class="pull-left">Unit Testing</span>
                      <span class="pull-right">15%</span>
                    </div>

                    <div class="progress progress-mini progress-warning">
                      <div style="width:15%" class="bar"></div>
                    </div>
                  </a>
                </li>

                <li>
                  <a href="#">
                    <div class="clearfix">
                      <span class="pull-left">Bug Fixes</span>
                      <span class="pull-right">90%</span>
                    </div>

                    <div class="progress progress-mini progress-success progress-striped active">
                      <div style="width:90%" class="bar"></div>
                    </div>
                  </a>
                </li>

                <li>
                  <a href="#">
                    See tasks with details
                    <i class="icon-arrow-right"></i>
                  </a>
                </li>
              </ul>
            </li>

            <li class="purple">
              <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                <i class="icon-bell-alt icon-only icon-animated-bell"></i>
                <span class="badge badge-important">8</span>
              </a>

              <ul class="pull-right dropdown-navbar navbar-pink dropdown-menu dropdown-caret dropdown-closer">
                <li class="nav-header">
                  <i class="icon-warning-sign"></i>
                  8 Notifications
                </li>

                <li>
                  <a href="#">
                    <div class="clearfix">
                      <span class="pull-left">
                        <i class="btn btn-mini no-hover btn-pink icon-comment"></i>
                        New Comments
                      </span>
                      <span class="pull-right badge badge-info">+12</span>
                    </div>
                  </a>
                </li>

                <li>
                  <a href="#">
                    <i class="btn btn-mini btn-primary icon-user"></i>
                    Bob just signed up as an editor ...
                  </a>
                </li>

                <li>
                  <a href="#">
                    <div class="clearfix">
                      <span class="pull-left">
                        <i class="btn btn-mini no-hover btn-success icon-shopping-cart"></i>
                        New Orders
                      </span>
                      <span class="pull-right badge badge-success">+8</span>
                    </div>
                  </a>
                </li>

                <li>
                  <a href="#">
                    <div class="clearfix">
                      <span class="pull-left">
                        <i class="btn btn-mini no-hover btn-info icon-twitter"></i>
                        Followers
                      </span>
                      <span class="pull-right badge badge-info">+11</span>
                    </div>
                  </a>
                </li>

                <li>
                  <a href="#">
                    See all notifications
                    <i class="icon-arrow-right"></i>
                  </a>
                </li>
              </ul>
            </li>

            <li class="green">
              <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                <i class="icon-envelope-alt icon-only icon-animated-vertical"></i>
                <span class="badge badge-success">5</span>
              </a>

              <ul class="pull-right dropdown-navbar dropdown-menu dropdown-caret dropdown-closer">
                <li class="nav-header">
                  <i class="icon-envelope"></i>
                  5 Messages
                </li>

                <li>
                  <a href="#">
                    <img src="/assets/avatar.png" class="msg-photo" alt="Alex's Avatar" />
                    <span class="msg-body">
                      <span class="msg-title">
                        <span class="blue">Alex:</span>
                        Ciao sociis natoque penatibus et auctor ...
                      </span>

                      <span class="msg-time">
                        <i class="icon-time"></i>
                        <span>a moment ago</span>
                      </span>
                    </span>
                  </a>
                </li>

                <li>
                  <a href="#">
                    <img src="/assets/avatar3.png" class="msg-photo" alt="Susan's Avatar" />
                    <span class="msg-body">
                      <span class="msg-title">
                        <span class="blue">Susan:</span>
                        Vestibulum id ligula porta felis euismod ...
                      </span>

                      <span class="msg-time">
                        <i class="icon-time"></i>
                        <span>20 minutes ago</span>
                      </span>
                    </span>
                  </a>
                </li>

                <li>
                  <a href="#">
                    <img src="/assets/avatar4.png" class="msg-photo" alt="Bob's Avatar" />
                    <span class="msg-body">
                      <span class="msg-title">
                        <span class="blue">Bob:</span>
                        Nullam quis risus eget urna mollis ornare ...
                      </span>

                      <span class="msg-time">
                        <i class="icon-time"></i>
                        <span>3:15 pm</span>
                      </span>
                    </span>
                  </a>
                </li>

                <li>
                  <a href="#">
                    See all messages
                    <i class="icon-arrow-right"></i>
                  </a>
                </li>
              </ul>
            </li>

            <li class="light-blue user-profile">
              <a data-toggle="dropdown" href="#" class="user-menu dropdown-toggle">
                <img class="nav-user-photo" src="/assets/user.jpg" alt="Jason's Photo" />
                <span id="user_info">
                  <small>Welcome,</small>
                  <%= current_user.name %>
                </span>

                <i class="icon-caret-down"></i>
              </a>

              <ul class="pull-right dropdown-menu dropdown-yellow dropdown-caret dropdown-closer" id="user_menu">
                <li>
                  <a href="#">
                    <i class="icon-cog"></i>
                    Settings
                  </a>
                </li>

                <li>
                  <a href="#">
                    <i class="icon-user"></i>
                    Profile
                  </a>
                </li>

                <li class="divider"></li>

                <li>

                  <%= link_to '<i class="icon-off"></i>Logout'.html_safe, destroy_user_session_path, :method=>'delete' %>
                    
                </li>
              </ul>
            </li>
          </ul><!--/.ace-nav-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title><%= content_for?(:title) ? yield(:title) : "Appfy" %></title>

    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Appfy" %>">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <!--basic styles-->
    <%= stylesheet_link_tag "application", :media => "all" %>

    <!--[if IE 7]>
      <link rel="stylesheet" href="assets/font-awesome-ie7.min.css" />
    <![endif]-->

    <!--page specific plugin styles-->

    <!--fonts-->

    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:400,300" />

    <!--ace styles-->

    <!--[if lte IE 8]>
      <link rel="stylesheet" href="assets/ace-ie.min.css" />
    <![endif]-->


    <%= csrf_meta_tags %>
    <%= yield(:head) %>

  </head>

  <body>


    <%= yield(:modal) %>

    <div class="navbar navbar-inverse">
      <div class="navbar-inner">
        <div class="container-fluid">

            <%= link_to "<small><i class='icon-leaf'></i> #{I18n.t('appfy_backend', :default => 'Appfy.cn backend Interface')}</small>".html_safe, user_path(current_user), :class => "brand" %>

          <%= render '/layouts/topleftnotifier' %>
        </div><!--/.container-fluid-->
      </div><!--/.navbar-inner-->
    </div>

    <div class="container-fluid" id="main-container">
      <a id="menu-toggler" href="#">
        <span></span>
      </a>

      <%= render '/layouts/leftmenu' %>


      <div id="main-content" class="clearfix">
        <div id="breadcrumbs">
          <ul class="breadcrumb">
            <li>
              <i class="icon-home"></i>
              <a href="#">Home</a>

              <span class="divider">
                <i class="icon-angle-right"></i>
              </span>
            </li>

            <li>
              <a href="#">Other Pages</a>

              <span class="divider">
                <i class="icon-angle-right"></i>
              </span>
            </li>
            <li class="active">Blank Page</li>
          </ul><!--.breadcrumb-->

          <div id="nav-search">
            <form class="form-search">
              <span class="input-icon">
                <input type="text" placeholder="Search ..." class="input-small search-query" id="nav-search-input" autocomplete="off" />
                <i class="icon-search" id="nav-search-icon"></i>
              </span>
            </form>
          </div><!--#nav-search-->
        </div>

        <div id="page-content" class="clearfix">
          <div class="row-fluid">
            <!--PAGE CONTENT BEGINS HERE-->
            <%= bootstrap_flash %>
            <%= yield %>


                <!-- DEBUG -->


            <!--PAGE CONTENT ENDS HERE-->
          </div><!--/row-->
        </div><!--/#page-content-->

        </div><!--/#ace-settings-container-->
      </div><!--/#main-content-->
    </div><!--/.fluid-container#main-container-->

    <a href="#" id="btn-scroll-up" class="btn btn-small btn-inverse">
      <i class="icon-double-angle-up icon-only bigger-110"></i>
    </a>
    <script type="text/javascript">
      current_page = '<%= current_page_name %>';
      current_app = '<%= current_app %>';

    </script>

    <%= javascript_include_tag "application" %>
    <%= yield(:js) %>

    <script type="text/javascript">
      $("#sidebar > a[href=\"#"+window.location.hash.substr(1)+"\"]").trigger("click");
    </script>
    <pre>
</pre>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title><%= content_for?(:title) ? yield(:title) : "Appfy" %></title>

    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Appfy" %>">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <!--basic styles-->
    <%= stylesheet_link_tag "application", :media => "all" %>

    <!--[if IE 7]>
      <link rel="stylesheet" href="assets/font-awesome-ie7.min.css" />
    <![endif]-->

    <!--page specific plugin styles-->

    <!--fonts-->

    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:400,300" />

    <!--ace styles-->

    <!--[if lte IE 8]>
      <link rel="stylesheet" href="assets/ace-ie.min.css" />
    <![endif]-->


    <%= csrf_meta_tags %>
    <%= yield(:head) %>

  </head>
	<body class="login-layout">
		<div class="container-fluid" id="main-container">
			<div id="main-content">
				<div class="row-fluid">
					<div class="span12">
						<div class="login-container">
							<div class="row-fluid">
								<div class="center">
									<h1>
										<i class="icon-leaf green"></i>
										<span class="red">Appfy.cn</span>
										<span class="white">应用后台</span>
									</h1>
									<h4 class="blue">&copy; 北京意得捷优科技有限公司</h4>
								</div>
							</div>

							<div class="space-6"></div>

							<div class="row-fluid">
								<div class="position-relative">
									<div id="login-box" class="visible widget-box no-border">
										<div class="widget-body">
											<%= yield %>
										</div>
									</div><!--/login-box-->
								</div><!--/position-relative-->
							</div>
						</div>
					</div><!--/span-->
				</div><!--/row-->
			</div>
		</div><!--/.fluid-container-->

		<!--basic scripts-->

    	<%= javascript_include_tag "application" %>
		<!--page specific plugin scripts-->

		<!--inline scripts related to this page-->

		<script type="text/javascript">
			function show_box(id) {
			 $('.widget-box.visible').removeClass('visible');
			 $('#'+id).addClass('visible');
			}
		</script>
	</body>
</html>